Open-avb: fix compilation error
  error: ordered comparison of pointer with integer zero ('timer_t' {aka 'void*'} and 'int')

Change-Id: I7d105598f2e349d50e279130f91ce0a4ea2b5127
(cherry picked from commit d3c423087302f1bc05aa2cbbe0115e09b0d7c070)